name: macos-matrix

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos-build_and_test:
    strategy:
      matrix:
        os: [macos-latest, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: printenv & installs
        run: |
          printenv
          if hash make; then make -v; else  brew install automake; fi
          if hash swift; then swift -version; else  brew install swift; fi
      - name: make
        run: |
          make all
